version: "3.7"

services:
  frontend:
    container_name: ${APP_NAME}
    image: testweb-server
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./frontend://etc/share/nginx/html/
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
